name: System Automation

on:
  push:
    paths:
      - ".github/workflows/system-automation.yml"
      - "scripts/**"
  workflow_dispatch:

jobs:
  automation:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      NORMAL_ENV: "Variable normal visible en los scripts"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Make Linux script executable
        if: runner.os == 'Linux'
        run: chmod +x scripts/linux-system.sh

      - name: Run Linux script
        if: runner.os == 'Linux'
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}   # <- secreto
        run: scripts/linux-system.sh

      - name: Run Windows script
        if: runner.os == 'Windows'
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}   # <- secreto
        run: powershell -ExecutionPolicy Bypass -File scripts/windows-system.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: system-automation-${{ matrix.os }}
          path: artifacts
